use UNIVER
---—
SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)[Средняя оценка]
FROM FACULTY,GROUPS,PROGRESS
WHERE FACULTY.FACULTY like 'ТОВ'
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT
union
SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)[Средняя оценка]
FROM FACULTY,GROUPS,PROGRESS
WHERE FACULTY.FACULTY like 'ХТиТ'
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT

--—

SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)[Средняя оценка]
FROM FACULTY,GROUPS,PROGRESS
WHERE FACULTY.FACULTY like 'ТОВ'
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT
union all
SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)[Средняя оценка]
FROM FACULTY,GROUPS,PROGRESS
WHERE FACULTY.FACULTY like 'ХТиТ'
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT

------

SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)[Средняя оценка]
FROM FACULTY,GROUPS,PROGRESS
WHERE FACULTY.FACULTY like 'ТОВ'
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT

INTERSECT

SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)[Средняя оценка]
FROM FACULTY,GROUPS,PROGRESS
WHERE FACULTY.FACULTY like 'ХТиТ'
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT


SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)[Средняя оценка]
FROM FACULTY,GROUPS,PROGRESS
WHERE FACULTY.FACULTY like 'ТОВ'
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT

EXCEPT

SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)[Средняя оценка]
FROM FACULTY,GROUPS,PROGRESS
WHERE FACULTY.FACULTY like 'ХТиТ'
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT


use ARTS_MyBase

select Пользователь.Покупатель_ID

from Пользователь

EXCEPT

select  Заказ.Номер_заказа

from  Заказ




