use UNIVER

SELECT FACULTY.FACULTY[‘акультет], GROUPS.PROFESSION[—пециальность],
round(avg(cast(PROGRESS.NOTE as float(4))),2)[—редн€€ оценка]
FROM FACULTY inner join GROUPS on FACULTY.FACULTY = GROUPS.FACULTY
inner join STUDENT on GROUPS.IDGROUP = STUDENT.IDGROUP
inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION


----4(2)
SELECT FACULTY.FACULTY[‘акультет], GROUPS.PROFESSION[специальность],
round(avg(cast(PROGRESS.NOTE as float(4))),2)[средн€€ оценка]
FROM FACULTY inner join GROUPS on FACULTY.FACULTY = GROUPS.FACULTY 
inner join STUDENT on GROUPS.IDGROUP = STUDENT.IDGROUP 
inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
where PROGRESS.SUBJECT in ('Ѕƒ','ќјиѕ')
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION