create tablespace TS_APA
DATAFILE 'E:\STUDY\DATABASE\ORACLE_Lab_2\TS_APA.dbf'
SIZE 7M
AUTOEXTEND ON NEXT 5M
MAXSIZE 30M



-- Временное табличное простарнство
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE TEMPORARY TABLESPACE TS_APA_TEMP_X
TEMPFILE 'TS_APA_X_TEMP.DFA'
SIZE 5M
AUTOEXTEND ON NEXT 3M
MAXSIZE 30M
EXTENT MANAGEMENT LOCAL;

drop tablespace TS_APA_TEMP

SELECT TABLESPACE_NAME FROM SYS.DBA_TABLESPACES; 

SELECT FILE_NAME, TABLESPACE_NAME FROM DBA_DATA_FILES;     




-- Роли

create role RL_APACORE;

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

GRANT CONNECT,CREATE SESSION, CREATE ANY TABLE,
DROP ANY TABLE, CREATE ANY VIEW,
DROP ANY VIEW, CREATE ANY PROCEDURE,
DROP ANY PROCEDURE TO RL_APACORE

SELECT * FROM DBA_ROLES WHERE ROLE LIKE '%RL%';



CREATE PROFILE PF_APACORE LIMIT
PASSWORD_LIFE_TIME 180 -- количество дней жизни пароля
SESSIONS_PER_USER 3 -- количество сессий пользователя
FAILED_LOGIN_ATTEMPTS 7 -- количество попыток входа
PASSWORD_LOCK_TIME 1 -- количество дней блокирования после ошибок
PASSWORD_REUSE_TIME 10  -- количество дней предупреждений о смене пароля
CONNECT_TIME 180 -- время соединения, минуты
IDLE_TIME 30 -- количество минут простоя


SELECT * FROM DBA_PROFILES;
SELECT * FROM DBA_PROFILES  WHERE PROFILE='PF_APACORE';
SELECT * FROM DBA_PROFILES  WHERE PROFILE='DEFAULT';


/*. Создайте пользователя с именем XXXCORE со следующими параметрами:
- табличное пространство по умолчанию: TS_XXX;
- табличное пространство для временных данных: TS_XXX_TEMP;
- профиль безопасности PF_XXXCORE;
- учетная запись разблокирована;
- срок действия пароля истек.  */
------------------- Task 8 ------------------
CREATE USER APACORE IDENTIFIED BY 12345
DEFAULT TABLESPACE TS_APA QUOTA UNLIMITED ON TS_APA
TEMPORARY TABLESPACE TS_APA_TEMP_X
PROFILE PF_APACORE
ACCOUNT UNLOCK
PASSWORD EXPIRE

SELECT * FROM dba_users WHERE USERNAME = 'APACORE';



-- 8

CREATE TABLESPACE APA_QDATA
    DATAFILE 'APA_QDATA.dbf'
    SIZE 10M
    AUTOEXTEND ON NEXT 3M
    MAXSIZE 100M
    EXTENT MANAGEMENT LOCAL;

ALTER TABLESPACE APA_QDATA OFFLINE;
ALTER TABLESPACE APA_QDATA ONLINE;

CREATE USER APA IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE TO APA;
ALTER USER APA QUOTA 2M ON ZPD_QDATA;   

CREATE TABLE APA_T1
    (
        id NUMBER,
        name VARCHAR2(20)
    )
    TABLESPACE APA_QDATA;

INSERT INTO APA_T1 VALUES (1, 'Paul');
INSERT INTO APA_T1 VALUES (2, 'Petya');
INSERT INTO APA_T1 VALUES (3, 'Grisha');

SELECT * FROM APA_T1;




